[package]
name = "ui-tray"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
ksni = "0.2"

# Used to spawn the control panel.
which = "6"

serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5"
libc = "0.2"
